### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by magush27** [jimblandy/spiral-calendar#7]
When I run `python gen_calendar.py ` on terminal it stops and I get the following syntax errors:

```
line 65
    def __init__(self,(realWidth, realHeight), pixelWidthHeight):
                        ^
SyntaxError: invalid syntax
```

```
line 78
    def line(self, (x1, y1), (x2, y2), **attributes):
                   ^
SyntaxError: invalid syntax
```
```
line 82
    def rect(self, (x, y), (width, height), **attributes):
                   ^
SyntaxError: invalid syntax
```
```
line 372, in <module>
    picture = SVGPicture(pageSizeInches, pageSize)
TypeError: __init__() missing 1 required positional argument: 'pixelWidthHeight'
```

Also it happens running `python gen_week.py`. I tried some ways to solve this but I don´t know much Python and I couldn't. Do you know what it can be? 
I´d like to try this code, thanks!

**Comment by jimblandy** [comment]
This code is Python 2, I'm afraid. You're probably running it with Python 3.

You might try:

    python2 gen_calendar.py

**Comment by magush27** [comment]
Thanks! It worked with Python 2

**Comment by jimblandy** [comment]
Great! I hope you enjoy the calendar.
